// <auto-generated />
using System;
using Domolov.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domolov.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DomolovDbContext))]
    [Migration("20260915175921_AddListingLocationAndLandSize")]
    partial class AddListingLocationAndLandSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domolov.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ListingId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloorText")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LandSizeText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rooms")
                        .HasColumnType("text");

                    b.Property<string>("SizeText")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("YearText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.NotificationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Triggers")
                        .HasColumnType("integer");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchId");

                    b.ToTable("NotificationRoutes");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "ObservedAt");

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.PushSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer");

                    b.Property<string>("NotifyErrorSummary")
                        .HasColumnType("text");

                    b.Property<int>("PagesScanned")
                        .HasColumnType("integer");

                    b.Property<int>("PriceChangeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchId", "Status");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.Watch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasCompletedBaseline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SearchUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("Watches");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.WatchSighting", b =>
                {
                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WatchId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("WatchSightings");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("Domolov.Domain.Entities.Listing", "Listing")
                        .WithOne("Bookmark")
                        .HasForeignKey("Domolov.Domain.Entities.Bookmark", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.NotificationRoute", b =>
                {
                    b.HasOne("Domolov.Domain.Entities.Watch", "Watch")
                        .WithMany("NotificationRoutes")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.PriceObservation", b =>
                {
                    b.HasOne("Domolov.Domain.Entities.Listing", "Listing")
                        .WithMany("Prices")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.ScanRun", b =>
                {
                    b.HasOne("Domolov.Domain.Entities.Watch", "Watch")
                        .WithMany("ScanRuns")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.WatchSighting", b =>
                {
                    b.HasOne("Domolov.Domain.Entities.Listing", "Listing")
                        .WithMany("Sightings")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domolov.Domain.Entities.Watch", "Watch")
                        .WithMany("Sightings")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.Listing", b =>
                {
                    b.Navigation("Bookmark");

                    b.Navigation("Prices");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("Domolov.Domain.Entities.Watch", b =>
                {
                    b.Navigation("NotificationRoutes");

                    b.Navigation("ScanRuns");

                    b.Navigation("Sightings");
                });
#pragma warning restore 612, 618
        }
    }
}
