// <auto-generated />
using System;
using Domolov.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domolov.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DomolovDbContext))]
    partial class DomolovDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domolov.Domain.Auth.OperatorSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("OperatorSessions");
                });

            modelBuilder.Entity("Domolov.Domain.Homes.Bookmark", b =>
                {
                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HomeId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Domolov.Domain.Homes.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveListingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("LandSizeM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("OffMarketAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("PriceChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PricePerM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("PrimaryListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text");

                    b.Property<int>("RepostCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RoomCount")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SizeM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPrice");

                    b.HasIndex("DismissedAt");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("OffMarketAt");

                    b.HasIndex("PriceChangedAt");

                    b.HasIndex("SeenAt");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domolov.Domain.Homes.HomeMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("State");

                    b.HasIndex("ListingId", "HomeId");

                    b.ToTable("HomeMatches");
                });

            modelBuilder.Entity("Domolov.Domain.Listings.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("DelistedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloorText")
                        .HasColumnType("text");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ImageHash")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("LandSizeM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("LandSizeText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedDescription")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedTitle")
                        .HasColumnType("text");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("PriceChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PricePerM2")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("RoomCount")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<string>("Rooms")
                        .HasColumnType("text");

                    b.Property<decimal?>("SizeM2")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("SizeText")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.Property<string>("YearText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DelistedAt");

                    b.HasIndex("HomeId");

                    b.HasIndex("ProviderId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("PropertyType", "RoomCount", "SizeM2");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Domolov.Domain.Listings.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "ObservedAt");

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("Domolov.Domain.Notifications.NotificationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Triggers")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WatchId");

                    b.ToTable("NotificationRoutes");
                });

            modelBuilder.Entity("Domolov.Domain.Push.WebPushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions", (string)null);
                });

            modelBuilder.Entity("Domolov.Domain.Retention.CleanupRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("BrowserProfileBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("DeletedArtifacts")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedHomes")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedListings")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedScanRuns")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedSessions")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("CleanupRuns");
                });

            modelBuilder.Entity("Domolov.Domain.Scans.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("CloudflareBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("CrawlReachedEnd")
                        .HasColumnType("boolean");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer");

                    b.Property<string>("NotifyErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PagesScanned")
                        .HasColumnType("integer");

                    b.Property<int>("PriceChangeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepostCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("WatchId", "Status");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("Domolov.Domain.Scans.ScanRunArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ScanRunId");

                    b.ToTable("ScanRunArtifacts");
                });

            modelBuilder.Entity("Domolov.Domain.Watches.Watch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CloudflareBlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CloudflareStrikeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasCompletedBaseline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SearchUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("SearchUrlChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Watches");
                });

            modelBuilder.Entity("Domolov.Domain.Watches.WatchSighting", b =>
                {
                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissedRunCount")
                        .HasColumnType("integer");

                    b.HasKey("WatchId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("WatchSightings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Domolov.Domain.Homes.Bookmark", b =>
                {
                    b.HasOne("Domolov.Domain.Homes.Home", null)
                        .WithOne("Bookmark")
                        .HasForeignKey("Domolov.Domain.Homes.Bookmark", "HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Homes.HomeMatch", b =>
                {
                    b.HasOne("Domolov.Domain.Homes.Home", null)
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domolov.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domolov.Domain.Homes.MatchSignals", "Signals", b1 =>
                        {
                            b1.Property<Guid>("HomeMatchId");

                            b1.Property<double?>("AttributeScore");

                            b1.Property<double?>("DescriptionSimilarity");

                            b1.PrimitiveCollection<string>("MatchedAttributes")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("MismatchedAttributes")
                                .IsRequired();

                            b1.Property<int?>("PhotoDistance");

                            b1.Property<double?>("PhotoScore");

                            b1.Property<double?>("TextScore");

                            b1.Property<double?>("TitleSimilarity");

                            b1.HasKey("HomeMatchId");

                            b1.ToTable("HomeMatches");

                            b1
                                .ToJson("Signals")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HomeMatchId");
                        });

                    b.Navigation("Signals")
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Listings.Listing", b =>
                {
                    b.HasOne("Domolov.Domain.Homes.Home", null)
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Listings.PriceObservation", b =>
                {
                    b.HasOne("Domolov.Domain.Listings.Listing", null)
                        .WithMany("Prices")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Notifications.NotificationRoute", b =>
                {
                    b.HasOne("Domolov.Domain.Watches.Watch", null)
                        .WithMany("NotificationRoutes")
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Scans.ScanRun", b =>
                {
                    b.HasOne("Domolov.Domain.Watches.Watch", "Watch")
                        .WithMany()
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Domolov.Domain.Scans.ScanRunArtifact", b =>
                {
                    b.HasOne("Domolov.Domain.Scans.ScanRun", null)
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Watches.WatchSighting", b =>
                {
                    b.HasOne("Domolov.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domolov.Domain.Watches.Watch", null)
                        .WithMany()
                        .HasForeignKey("WatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domolov.Domain.Homes.Home", b =>
                {
                    b.Navigation("Bookmark");
                });

            modelBuilder.Entity("Domolov.Domain.Listings.Listing", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Domolov.Domain.Watches.Watch", b =>
                {
                    b.Navigation("NotificationRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
