<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Domolov.Application\Domolov.Application.csproj" />
    <ProjectReference Include="..\Domolov.Domain\Domolov.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="WebPush" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Scanning\Fixtures\*.json" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Domolov.UnitTests" />
    <InternalsVisibleTo Include="Domolov.IntegrationTests" />
  </ItemGroup>
</Project>
