/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session (401 when signed out) */
        get: operations["GetSession"];
        put?: never;
        /** Sign in with the operator password; sets the session cookie */
        post: operations["SignIn"];
        /** Sign out of this browser */
        delete: operations["SignOut"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active sessions */
        get: operations["ListSessions"];
        put?: never;
        post?: never;
        /** Revoke every session, including this one */
        delete: operations["SignOutEverywhere"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one session */
        delete: operations["RevokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watches with their routes, last scan and next run */
        get: operations["ListWatches"];
        put?: never;
        /** Create a Watch (optionally with its first notification route); the first scan is queued */
        post: operations["CreateWatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Watch (ETag for conditional updates) */
        get: operations["GetWatch"];
        put?: never;
        post?: never;
        /** Delete a Watch with its routes, scans and sightings */
        delete: operations["DeleteWatch"];
        options?: never;
        head?: never;
        /** Rename, reschedule, change the search URL, or pause/resume a Watch */
        patch: operations["UpdateWatch"];
        trace?: never;
    };
    "/api/watches/{id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a scan now (Run now); returns the active ScanRun */
        post: operations["RunWatchNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-url-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check whether a pasted search URL is supported and suggest a Watch name */
        post: operations["CheckSearchUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bookmarked Homes grouped by stage */
        get: operations["GetBookmarkBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline numbers, Unseen Homes, price drops, Watch health and active scans */
        get: operations["GetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read-only server configuration and capability flags */
        get: operations["GetSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches/{watchId}/notification-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a Watch's notification routes */
        get: operations["ListNotificationRoutes"];
        put?: never;
        /** Add a notification route */
        post: operations["CreateNotificationRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watches/{watchId}/notification-routes/{routeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a route */
        delete: operations["DeleteNotificationRoute"];
        options?: never;
        head?: never;
        /** Change a route's destination, triggers or enabled flag */
        patch: operations["UpdateNotificationRoute"];
        trace?: never;
    };
    "/api/watches/{watchId}/notification-routes/{routeId}/test-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a sample notification through the route right now */
        post: operations["SendTestNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Homes feed: one card per Home with filters, sorting and paging */
        get: operations["SearchHomes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A Home with every ad in its history, price history and possible matches */
        get: operations["GetHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/{id}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Bookmark a Home or change its stage and note */
        put: operations["SetBookmark"];
        post?: never;
        /** Remove a Home's Bookmark */
        delete: operations["RemoveBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/{id}/dismissal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Dismiss a Home: hidden from feeds and never notified (removes its Bookmark) */
        put: operations["DismissHome"];
        post?: never;
        /** Undo a dismissal */
        delete: operations["RestoreHome"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a Home as seen */
        put: operations["MarkHomeSeen"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark every Unseen Home as seen */
        post: operations["MarkAllHomesSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/{id}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link another ad to this Home (same home) */
        post: operations["LinkListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homes/{id}/listings/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Split an ad off this Home (not the same home); returns the new Home */
        delete: operations["UnlinkListing"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches to review (possible by default) */
        get: operations["ListHomeMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home-matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm (same home) or reject (different homes) a possible match */
        patch: operations["ReviewHomeMatch"];
        trace?: never;
    };
    "/api/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One ad with its price history */
        get: operations["GetListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete every Listing and Home (danger zone) */
        delete: operations["DeleteAllListings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ScanRuns, newest first */
        get: operations["ListScanRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events: 'scanRun' on every ScanRun change, 'ping' every 25 s */
        get: operations["ScanRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One ScanRun */
        get: operations["GetScanRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics captured during a ScanRun (Cloudflare screenshots, HTML, headers) */
        get: operations["ListScanArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{id}/artifacts/{artifactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an artifact */
        get: operations["GetScanArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Database size, largest tables and cleanup status */
        get: operations["GetStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/cleanups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the worker to run the retention cleanup now */
        post: operations["RunCleanupNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store this browser's Web Push subscription */
        post: operations["SubscribePush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/push-subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a Web Push subscription */
        delete: operations["UnsubscribePush"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The Bookmark board: Homes grouped by stage. */
        BookmarkBoardResponse: {
            columns: components["schemas"]["BookmarkColumnResponse"][];
        };
        /** @description One board column. */
        BookmarkColumnResponse: {
            stage: components["schemas"]["BookmarkStage"];
            homes: components["schemas"]["HomeSummaryResponse"][];
        };
        /** @description A Bookmark as returned by the API. */
        BookmarkResponse: {
            stage: components["schemas"]["BookmarkStage"];
            note: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description Where the operator is with a Bookmarked Home. Ordered from least to most advanced.
         * @enum {unknown}
         */
        BookmarkStage: "interested" | "contacted" | "viewingScheduled" | "viewed" | "offerMade" | "rejected";
        /** @description A finished or running cleanup. */
        CleanupRunResponse: {
            /** Format: uuid */
            id: string;
            isManual: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: null | string;
            /** Format: int32 */
            deletedListings: number;
            /** Format: int32 */
            deletedHomes: number;
            /** Format: int32 */
            deletedScanRuns: number;
            /** Format: int32 */
            deletedArtifacts: number;
            /** Format: int32 */
            deletedSessions: number;
            /** Format: int64 */
            browserProfileBytes: null | number;
            error: null | string;
        };
        /** @description Number of Homes affected by a bulk operation. */
        CountResponse: {
            /** Format: int32 */
            count: number;
        };
        /** @description Payload for adding a NotificationRoute. */
        CreateNotificationRouteRequest: {
            channel: components["schemas"]["NotificationChannel"];
            destination: string;
            triggers?: null | components["schemas"]["NotificationTrigger"][];
            /** @default true */
            isEnabled: boolean;
        };
        /** @description Payload for creating a Watch, optionally with its first notification route. */
        CreateWatchRequest: {
            name: string;
            searchUrl: string;
            cron?: null | string;
            /** @default false */
            isPaused: boolean;
            initialRoute?: null | components["schemas"]["CreateNotificationRouteRequest"];
        };
        /** @description Everything the dashboard shows. */
        DashboardResponse: {
            stats: components["schemas"]["DashboardStats"];
            unseen: components["schemas"]["HomeSummaryResponse"][];
            priceDrops: components["schemas"]["HomeSummaryResponse"][];
            watches: components["schemas"]["WatchResponse"][];
            activeScans: components["schemas"]["ScanRunResponse"][];
        };
        /** @description Headline numbers for the dashboard. */
        DashboardStats: {
            /** Format: int32 */
            activeWatches: number;
            /** Format: int32 */
            pausedWatches: number;
            /** Format: int32 */
            onMarketHomes: number;
            /** Format: int32 */
            unseenHomes: number;
            /** Format: int32 */
            newHomes24h: number;
            /** Format: int32 */
            priceDrops7d: number;
            /** Format: int32 */
            reposts7d: number;
            /** Format: int32 */
            possibleMatches: number;
            /** Format: int32 */
            bookmarkedHomes: number;
        };
        /** @description Number of Listings removed. */
        DeleteAllListingsResponse: {
            /** Format: int32 */
            deleted: number;
        };
        /** @enum {unknown} */
        DismissedFilter: "exclude" | "include" | "only" | null;
        /**
         * @description Which parts of Domolov this process runs.
         * @enum {unknown}
         */
        DomolovRole: "all" | "api" | "worker";
        /** @description Everything the Home page shows. */
        HomeDetailResponse: {
            home: components["schemas"]["HomeSummaryResponse"];
            description: null | string;
            yearText: null | string;
            listings: components["schemas"]["HomeListingResponse"][];
            priceHistory: components["schemas"]["PricePointResponse"][];
            /** Format: int32 */
            timeOnMarketDays: number;
            possibleMatches: components["schemas"]["HomeMatchResponse"][];
        };
        /** @description One ad in the Home's history. */
        HomeListingResponse: {
            /** Format: uuid */
            id: string;
            providerId: string;
            externalId: string;
            url: string;
            title: string;
            imageUrl: null | string;
            /** Format: double */
            price: null | number;
            currency: string;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            delistedAt: null | string;
            role: components["schemas"]["HomeListingRole"];
            watches: components["schemas"]["WatchRefResponse"][];
        };
        /**
         * @description Role of a Listing within its Home's history.
         * @enum {unknown}
         */
        HomeListingRole: "original" | "repost" | "duplicate";
        /** @description A HomeMatch with both sides for side-by-side review. */
        HomeMatchResponse: {
            /** Format: uuid */
            id: string;
            state: components["schemas"]["HomeMatchState"];
            /** Format: double */
            score: number;
            signals: components["schemas"]["MatchSignalsResponse"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            reviewedAt: null | string;
            listing: components["schemas"]["MatchListingResponse"];
            home: components["schemas"]["HomeSummaryResponse"];
            homePrimaryListing: null | components["schemas"]["MatchListingResponse"];
        };
        /**
         * @description Lifecycle of a HomeMatch.
         * @enum {unknown}
         */
        HomeMatchState: "autoLinked" | "possible" | "confirmed" | "rejected";
        /** @enum {unknown} */
        HomeSort: "newest" | "priceAsc" | "priceDesc" | "priceDrop" | "pricePerM2" | "size" | "recentlySeen" | null;
        /** @description A Home card: the Home plus key facts of its Primary Listing. */
        HomeSummaryResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            imageUrl: null | string;
            location: null | string;
            propertyType: null | string;
            /** Format: double */
            roomCount: null | number;
            rooms: null | string;
            /** Format: double */
            sizeM2: null | number;
            sizeText: null | string;
            /** Format: double */
            landSizeM2: null | number;
            landSizeText: null | string;
            floorText: null | string;
            /** Format: int32 */
            yearBuilt: null | number;
            /** Format: double */
            price: null | number;
            /** Format: double */
            previousPrice: null | number;
            currency: string;
            /** Format: date-time */
            priceChangedAt: null | string;
            /** Format: double */
            pricePerM2: null | number;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            offMarketAt: null | string;
            isUnseen: boolean;
            isDismissed: boolean;
            /** Format: int32 */
            listingCount: number;
            /** Format: int32 */
            activeListingCount: number;
            /** Format: int32 */
            repostCount: number;
            /** Format: uuid */
            primaryListingId: null | string;
            url: null | string;
            providerId: null | string;
            bookmark: null | components["schemas"]["BookmarkResponse"];
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** @description Manually link an ad to a Home. */
        LinkListingRequest: {
            /** Format: uuid */
            listingId: string;
        };
        /** @description One ad with its price history and the Watches that sighted it. */
        ListingDetailResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            homeId: string;
            providerId: string;
            externalId: string;
            url: string;
            title: string;
            imageUrl: null | string;
            description: null | string;
            propertyType: null | string;
            rooms: null | string;
            sizeText: null | string;
            yearText: null | string;
            floorText: null | string;
            location: null | string;
            landSizeText: null | string;
            /** Format: double */
            sizeM2: null | number;
            /** Format: double */
            landSizeM2: null | number;
            /** Format: double */
            roomCount: null | number;
            /** Format: int32 */
            yearBuilt: null | number;
            /** Format: double */
            price: null | number;
            /** Format: double */
            previousPrice: null | number;
            currency: string;
            /** Format: double */
            pricePerM2: null | number;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            delistedAt: null | string;
            prices: components["schemas"]["PricePointResponse"][];
            watches: components["schemas"]["WatchRefResponse"][];
        };
        /** @description Sign-in payload. */
        LoginRequest: {
            password: string;
        };
        /** @description Mark Homes seen up to a point in time (defaults to now). */
        MarkAllSeenRequest: {
            /** Format: date-time */
            before?: null | string;
        };
        /** @enum {unknown} */
        MarketStatus: "onMarket" | "offMarket" | "all" | null;
        /** @description The ad side of a HomeMatch. */
        MatchListingResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            homeId: string;
            title: string;
            url: string;
            imageUrl: null | string;
            /** Format: double */
            price: null | number;
            currency: string;
            location: null | string;
            propertyType: null | string;
            rooms: null | string;
            sizeText: null | string;
            landSizeText: null | string;
            floorText: null | string;
            yearText: null | string;
            description: null | string;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            delistedAt: null | string;
        };
        /** @description Matching settings shown in the UI. */
        MatchSettingsResponse: {
            /** Format: double */
            autoLinkScore: number;
            /** Format: double */
            possibleScore: number;
        };
        /** @description Why two ads look like the same Home. */
        MatchSignalsResponse: {
            /** Format: int32 */
            photoDistance: null | number;
            /** Format: double */
            photoScore: null | number;
            /** Format: double */
            titleSimilarity: null | number;
            /** Format: double */
            descriptionSimilarity: null | number;
            /** Format: double */
            textScore: null | number;
            /** Format: double */
            attributeScore: null | number;
            matchedAttributes: string[];
            mismatchedAttributes: string[];
        };
        /**
         * @description Outbound notification channel type.
         * @enum {unknown}
         */
        NotificationChannel: "discord" | "telegram" | "email" | "webPush";
        /** @description A NotificationRoute as returned by the API. */
        NotificationRouteResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            watchId: string;
            channel: components["schemas"]["NotificationChannel"];
            destination: string;
            triggers: components["schemas"]["NotificationTrigger"][];
            isEnabled: boolean;
            /** Format: uint32 */
            version: number;
        };
        /** @description Flags describing when a NotificationRoute should fire. */
        NotificationTrigger: string;
        /** @description A page of results with the total count. */
        PagedResponseOfHomeSummaryResponse: {
            items: components["schemas"]["HomeSummaryResponse"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description A page of results with the total count. */
        PagedResponseOfScanRunResponse: {
            items: components["schemas"]["ScanRunResponse"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        /** @description A price point of one of the Home's Listings. */
        PricePointResponse: {
            /** Format: uuid */
            listingId: string;
            /** Format: date-time */
            observedAt: string;
            /** Format: double */
            amount: number;
            currency: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @description A browser push subscription (from PushSubscription.toJSON()). */
        PushSubscriptionRequest: {
            /** Format: uri */
            endpoint: string;
            p256dh: string;
            auth: string;
        };
        /** @description The stored subscription id (used to unsubscribe). */
        PushSubscriptionResponse: {
            /** Format: uuid */
            id: string;
        };
        /** @description Retention settings shown in the UI. */
        RetentionSettingsResponse: {
            /** Format: int32 */
            delistedDays: number;
            /** Format: int32 */
            orphanListingDays: number;
            /** Format: int32 */
            scanRunDays: number;
            /** Format: int32 */
            scanRunKeepPerWatch: number;
            /** Format: int32 */
            artifactDays: number;
            /** Format: int32 */
            sessionDays: number;
            dailyAt: string;
        };
        /** @description Confirm or reject a Possible match. */
        ReviewMatchRequest: {
            state: components["schemas"]["HomeMatchState"];
        };
        /**
         * @description Kind of diagnostic captured during a ScanRun.
         * @enum {unknown}
         */
        ScanArtifactKind: "screenshot" | "html" | "headers";
        /** @description Metadata of a diagnostic artifact. */
        ScanArtifactResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            scanRunId: string;
            kind: components["schemas"]["ScanArtifactKind"];
            label: string;
            contentType: string;
            /** Format: int32 */
            sizeBytes: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description A ScanRun as returned by the API and pushed over SSE. */
        ScanRunResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            watchId: string;
            watchName: string;
            status: components["schemas"]["ScanRunStatus"];
            isManual: boolean;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            startedAt: null | string;
            /** Format: date-time */
            finishedAt: null | string;
            /** Format: int32 */
            pagesScanned: number;
            /** Format: int32 */
            newCount: number;
            /** Format: int32 */
            priceChangeCount: number;
            /** Format: int32 */
            repostCount: number;
            errorSummary: null | string;
            notifyErrorSummary: null | string;
            cloudflareBlocked: boolean;
            crawlReachedEnd: boolean;
            /** Format: int32 */
            artifactCount: number;
        };
        /**
         * @description Lifecycle status of a ScanRun.
         * @enum {unknown}
         */
        ScanRunStatus: "queued" | "running" | "baseline" | "succeeded" | "failed" | "interrupted";
        /** @description Asks whether a pasted search URL is supported. */
        SearchUrlCheckRequest: {
            url: string;
        };
        /** @description Result of a search URL check, with a suggested Watch name. */
        SearchUrlCheckResponse: {
            supported: boolean;
            providerId: null | string;
            suggestedName: null | string;
            problem: null | string;
        };
        /** @description A session in the session list. */
        SessionListItem: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            userAgent: null | string;
            ipAddress: null | string;
            isCurrent: boolean;
        };
        /** @description The current session. */
        SessionResponse: {
            name: string;
            /** Format: uuid */
            sessionId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Create or update a Bookmark. */
        SetBookmarkRequest: {
            stage: components["schemas"]["BookmarkStage"];
            note: null | string;
        };
        /** @description Read-only server configuration and capability flags. */
        SettingsResponse: {
            version: string;
            timeZone: string;
            role: components["schemas"]["DomolovRole"];
            /** Format: int32 */
            maxConcurrentScans: number;
            /** Format: int32 */
            scanCooldownMs: number;
            /** Format: int32 */
            cloudflareChallengeWaitMs: number;
            browserHeadless: boolean;
            fakeProvider: boolean;
            telegramConfigured: boolean;
            smtpConfigured: boolean;
            vapidConfigured: boolean;
            vapidPublicKey: null | string;
            publicUrl: null | string;
            retention: components["schemas"]["RetentionSettingsResponse"];
            match: components["schemas"]["MatchSettingsResponse"];
        };
        SseItemOfScanRunResponse: {
            data?: components["schemas"]["ScanRunResponse"];
            eventType?: null | string;
            eventId?: null | string;
            reconnectionInterval?: null | string;
        };
        /** @description Storage usage and cleanup status. */
        StorageResponse: {
            /** Format: int64 */
            databaseBytes: number;
            tables: components["schemas"]["TableStorage"][];
            lastCleanup: null | components["schemas"]["CleanupRunResponse"];
            /** Format: date-time */
            nextCleanupAt: null | string;
            retention: components["schemas"]["RetentionSettingsResponse"];
        };
        /** @description Size and approximate row count of one table. */
        TableStorage: {
            name: string;
            /** Format: int64 */
            bytes: number;
            /** Format: int64 */
            approximateRows: number;
        };
        /** @description Outcome of sending a test notification. */
        TestDeliveryResponse: {
            ok: boolean;
            error: null | string;
        };
        /** @description Partial update of a NotificationRoute. */
        UpdateNotificationRouteRequest: {
            destination?: null | string;
            triggers?: null | components["schemas"]["NotificationTrigger"][];
            isEnabled?: null | boolean;
        };
        /** @description Partial update of a Watch; omitted fields stay unchanged. */
        UpdateWatchRequest: {
            name?: null | string;
            searchUrl?: null | string;
            cron?: null | string;
            isPaused?: null | boolean;
        };
        /** @description A Watch that sighted a Listing. */
        WatchRefResponse: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @description A Watch as returned by the API. */
        WatchResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            providerId: string;
            searchUrl: string;
            cron: string;
            isPaused: boolean;
            hasCompletedBaseline: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastScannedAt: null | string;
            /** Format: date-time */
            nextRunAt: null | string;
            /** Format: int32 */
            cloudflareStrikeCount: number;
            /** Format: date-time */
            cloudflareBlockedUntil: null | string;
            /** Format: int32 */
            listingCount: number;
            lastScan: null | components["schemas"]["ScanRunResponse"];
            routes: components["schemas"]["NotificationRouteResponse"][];
            /** Format: uint32 */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    SignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SignOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItem"][];
                };
            };
        };
    };
    SignOutEverywhere: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RevokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListWatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"][];
                };
            };
        };
    };
    CreateWatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetWatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteWatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateWatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RunWatchNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CheckSearchUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchUrlCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchUrlCheckResponse"];
                };
            };
        };
    };
    GetBookmarkBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkBoardResponse"];
                };
            };
        };
    };
    GetDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    GetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    ListNotificationRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRouteResponse"][];
                };
            };
        };
    };
    CreateNotificationRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotificationRouteRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRouteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteNotificationRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchId: string;
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateNotificationRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchId: string;
                routeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationRouteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRouteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SendTestNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchId: string;
                routeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDeliveryResponse"];
                };
            };
        };
    };
    SearchHomes: {
        parameters: {
            query?: {
                WatchId?: string;
                Q?: string;
                Status?: components["schemas"]["MarketStatus"];
                Bookmarked?: boolean;
                Stage?: components["schemas"]["BookmarkStage"];
                Unseen?: boolean;
                Dismissed?: components["schemas"]["DismissedFilter"];
                Reposted?: boolean;
                HasDuplicates?: boolean;
                MinPrice?: number;
                MaxPrice?: number;
                MinSize?: number;
                MaxSize?: number;
                MaxPricePerM2?: number;
                PropertyType?: string;
                MinRooms?: number;
                Sort?: components["schemas"]["HomeSort"];
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponseOfHomeSummaryResponse"];
                };
            };
        };
    };
    GetHome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SetBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBookmarkRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    RemoveBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DismissHome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RestoreHome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarkHomeSeen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarkAllHomesSeen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkAllSeenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResponse"];
                };
            };
        };
    };
    LinkListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkListingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeDetailResponse"];
                };
            };
        };
    };
    UnlinkListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                listingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeSummaryResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListHomeMatches: {
        parameters: {
            query?: {
                state?: components["schemas"]["HomeMatchState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeMatchResponse"][];
                };
            };
        };
    };
    ReviewHomeMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewMatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeMatchResponse"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteAllListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAllListingsResponse"];
                };
            };
        };
    };
    ListScanRuns: {
        parameters: {
            query?: {
                watchId?: string;
                status?: components["schemas"]["ScanRunStatus"];
                active?: boolean;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResponseOfScanRunResponse"];
                };
            };
        };
    };
    ScanRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseItemOfScanRunResponse"];
                };
            };
        };
    };
    GetScanRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListScanArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanArtifactResponse"][];
                };
            };
        };
    };
    GetScanArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                artifactId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
        };
    };
    RunCleanupNow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscriptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    UnsubscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
